const colors = {
    red: "red",
    green: "green",
    blue: "blue",
    yellow: "yellow",
    white: "white",
    black: "black",
    orange: "orange",
    purple: "purple",
    pink: "pink",
    brown: "brown",
    gray: "gray",
    darkGray: "darkGray",
    lightGray: "lightGray",
    darkBlue: "darkBlue",
    lightBlue: "lightBlue",
    darkGreen: "darkGreen",
    lightGreen: "lightGreen",
    darkRed: "darkRed",
    lightRed: "lightRed",
    darkYellow: "darkYellow",
    lightYellow: "lightYellow",
    darkCyan: "darkCyan",
    lightCyan: "lightCyan",
    darkMagenta: "darkMagenta",
    secondary: "#737373",
    appDefaultColor: "#1976d2"
}

export default colors;